/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LearnIndexRouteImport } from './routes/learn.index'
import { Route as LearnUnderstandRouteImport } from './routes/learn.understand'
import { Route as LearnSupportRouteImport } from './routes/learn.support'
import { Route as LearnJourneyRouteImport } from './routes/learn.journey'
import { Route as LearnConnectRouteImport } from './routes/learn.connect'
import { Route as LearnCoachRouteImport } from './routes/learn.coach'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as LearnUnderstandIndexRouteImport } from './routes/learn.understand.index'
import { Route as LearnSupportIndexRouteImport } from './routes/learn.support.index'
import { Route as LearnConnectIndexRouteImport } from './routes/learn.connect.index'
import { Route as LearnCoachIndexRouteImport } from './routes/learn.coach.index'
import { Route as LearnUnderstandTopicRouteImport } from './routes/learn.understand.$topic'
import { Route as LearnSupportResourceRouteImport } from './routes/learn.support.$resource'
import { Route as LearnConnectSituationRouteImport } from './routes/learn.connect.$situation'
import { Route as LearnCoachThreadIdRouteImport } from './routes/learn.coach.$threadId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/learn/',
  path: '/learn/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnUnderstandRoute = LearnUnderstandRouteImport.update({
  id: '/learn/understand',
  path: '/learn/understand',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnSupportRoute = LearnSupportRouteImport.update({
  id: '/learn/support',
  path: '/learn/support',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnJourneyRoute = LearnJourneyRouteImport.update({
  id: '/learn/journey',
  path: '/learn/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnConnectRoute = LearnConnectRouteImport.update({
  id: '/learn/connect',
  path: '/learn/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnCoachRoute = LearnCoachRouteImport.update({
  id: '/learn/coach',
  path: '/learn/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnUnderstandIndexRoute = LearnUnderstandIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LearnUnderstandRoute,
} as any)
const LearnSupportIndexRoute = LearnSupportIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LearnSupportRoute,
} as any)
const LearnConnectIndexRoute = LearnConnectIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LearnConnectRoute,
} as any)
const LearnCoachIndexRoute = LearnCoachIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LearnCoachRoute,
} as any)
const LearnUnderstandTopicRoute = LearnUnderstandTopicRouteImport.update({
  id: '/$topic',
  path: '/$topic',
  getParentRoute: () => LearnUnderstandRoute,
} as any)
const LearnSupportResourceRoute = LearnSupportResourceRouteImport.update({
  id: '/$resource',
  path: '/$resource',
  getParentRoute: () => LearnSupportRoute,
} as any)
const LearnConnectSituationRoute = LearnConnectSituationRouteImport.update({
  id: '/$situation',
  path: '/$situation',
  getParentRoute: () => LearnConnectRoute,
} as any)
const LearnCoachThreadIdRoute = LearnCoachThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => LearnCoachRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/chat': typeof ApiChatRoute
  '/learn/coach': typeof LearnCoachRouteWithChildren
  '/learn/connect': typeof LearnConnectRouteWithChildren
  '/learn/journey': typeof LearnJourneyRoute
  '/learn/support': typeof LearnSupportRouteWithChildren
  '/learn/understand': typeof LearnUnderstandRouteWithChildren
  '/learn/': typeof LearnIndexRoute
  '/learn/coach/$threadId': typeof LearnCoachThreadIdRoute
  '/learn/connect/$situation': typeof LearnConnectSituationRoute
  '/learn/support/$resource': typeof LearnSupportResourceRoute
  '/learn/understand/$topic': typeof LearnUnderstandTopicRoute
  '/learn/coach/': typeof LearnCoachIndexRoute
  '/learn/connect/': typeof LearnConnectIndexRoute
  '/learn/support/': typeof LearnSupportIndexRoute
  '/learn/understand/': typeof LearnUnderstandIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/chat': typeof ApiChatRoute
  '/learn/journey': typeof LearnJourneyRoute
  '/learn': typeof LearnIndexRoute
  '/learn/coach/$threadId': typeof LearnCoachThreadIdRoute
  '/learn/connect/$situation': typeof LearnConnectSituationRoute
  '/learn/support/$resource': typeof LearnSupportResourceRoute
  '/learn/understand/$topic': typeof LearnUnderstandTopicRoute
  '/learn/coach': typeof LearnCoachIndexRoute
  '/learn/connect': typeof LearnConnectIndexRoute
  '/learn/support': typeof LearnSupportIndexRoute
  '/learn/understand': typeof LearnUnderstandIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/chat': typeof ApiChatRoute
  '/learn/coach': typeof LearnCoachRouteWithChildren
  '/learn/connect': typeof LearnConnectRouteWithChildren
  '/learn/journey': typeof LearnJourneyRoute
  '/learn/support': typeof LearnSupportRouteWithChildren
  '/learn/understand': typeof LearnUnderstandRouteWithChildren
  '/learn/': typeof LearnIndexRoute
  '/learn/coach/$threadId': typeof LearnCoachThreadIdRoute
  '/learn/connect/$situation': typeof LearnConnectSituationRoute
  '/learn/support/$resource': typeof LearnSupportResourceRoute
  '/learn/understand/$topic': typeof LearnUnderstandTopicRoute
  '/learn/coach/': typeof LearnCoachIndexRoute
  '/learn/connect/': typeof LearnConnectIndexRoute
  '/learn/support/': typeof LearnSupportIndexRoute
  '/learn/understand/': typeof LearnUnderstandIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/api/chat'
    | '/learn/coach'
    | '/learn/connect'
    | '/learn/journey'
    | '/learn/support'
    | '/learn/understand'
    | '/learn/'
    | '/learn/coach/$threadId'
    | '/learn/connect/$situation'
    | '/learn/support/$resource'
    | '/learn/understand/$topic'
    | '/learn/coach/'
    | '/learn/connect/'
    | '/learn/support/'
    | '/learn/understand/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/api/chat'
    | '/learn/journey'
    | '/learn'
    | '/learn/coach/$threadId'
    | '/learn/connect/$situation'
    | '/learn/support/$resource'
    | '/learn/understand/$topic'
    | '/learn/coach'
    | '/learn/connect'
    | '/learn/support'
    | '/learn/understand'
  id:
    | '__root__'
    | '/'
    | '/sitemap.xml'
    | '/api/chat'
    | '/learn/coach'
    | '/learn/connect'
    | '/learn/journey'
    | '/learn/support'
    | '/learn/understand'
    | '/learn/'
    | '/learn/coach/$threadId'
    | '/learn/connect/$situation'
    | '/learn/support/$resource'
    | '/learn/understand/$topic'
    | '/learn/coach/'
    | '/learn/connect/'
    | '/learn/support/'
    | '/learn/understand/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiChatRoute: typeof ApiChatRoute
  LearnCoachRoute: typeof LearnCoachRouteWithChildren
  LearnConnectRoute: typeof LearnConnectRouteWithChildren
  LearnJourneyRoute: typeof LearnJourneyRoute
  LearnSupportRoute: typeof LearnSupportRouteWithChildren
  LearnUnderstandRoute: typeof LearnUnderstandRouteWithChildren
  LearnIndexRoute: typeof LearnIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/': {
      id: '/learn/'
      path: '/learn'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/understand': {
      id: '/learn/understand'
      path: '/learn/understand'
      fullPath: '/learn/understand'
      preLoaderRoute: typeof LearnUnderstandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/support': {
      id: '/learn/support'
      path: '/learn/support'
      fullPath: '/learn/support'
      preLoaderRoute: typeof LearnSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/journey': {
      id: '/learn/journey'
      path: '/learn/journey'
      fullPath: '/learn/journey'
      preLoaderRoute: typeof LearnJourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/connect': {
      id: '/learn/connect'
      path: '/learn/connect'
      fullPath: '/learn/connect'
      preLoaderRoute: typeof LearnConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/coach': {
      id: '/learn/coach'
      path: '/learn/coach'
      fullPath: '/learn/coach'
      preLoaderRoute: typeof LearnCoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/understand/': {
      id: '/learn/understand/'
      path: '/'
      fullPath: '/learn/understand/'
      preLoaderRoute: typeof LearnUnderstandIndexRouteImport
      parentRoute: typeof LearnUnderstandRoute
    }
    '/learn/support/': {
      id: '/learn/support/'
      path: '/'
      fullPath: '/learn/support/'
      preLoaderRoute: typeof LearnSupportIndexRouteImport
      parentRoute: typeof LearnSupportRoute
    }
    '/learn/connect/': {
      id: '/learn/connect/'
      path: '/'
      fullPath: '/learn/connect/'
      preLoaderRoute: typeof LearnConnectIndexRouteImport
      parentRoute: typeof LearnConnectRoute
    }
    '/learn/coach/': {
      id: '/learn/coach/'
      path: '/'
      fullPath: '/learn/coach/'
      preLoaderRoute: typeof LearnCoachIndexRouteImport
      parentRoute: typeof LearnCoachRoute
    }
    '/learn/understand/$topic': {
      id: '/learn/understand/$topic'
      path: '/$topic'
      fullPath: '/learn/understand/$topic'
      preLoaderRoute: typeof LearnUnderstandTopicRouteImport
      parentRoute: typeof LearnUnderstandRoute
    }
    '/learn/support/$resource': {
      id: '/learn/support/$resource'
      path: '/$resource'
      fullPath: '/learn/support/$resource'
      preLoaderRoute: typeof LearnSupportResourceRouteImport
      parentRoute: typeof LearnSupportRoute
    }
    '/learn/connect/$situation': {
      id: '/learn/connect/$situation'
      path: '/$situation'
      fullPath: '/learn/connect/$situation'
      preLoaderRoute: typeof LearnConnectSituationRouteImport
      parentRoute: typeof LearnConnectRoute
    }
    '/learn/coach/$threadId': {
      id: '/learn/coach/$threadId'
      path: '/$threadId'
      fullPath: '/learn/coach/$threadId'
      preLoaderRoute: typeof LearnCoachThreadIdRouteImport
      parentRoute: typeof LearnCoachRoute
    }
  }
}

interface LearnCoachRouteChildren {
  LearnCoachThreadIdRoute: typeof LearnCoachThreadIdRoute
  LearnCoachIndexRoute: typeof LearnCoachIndexRoute
}

const LearnCoachRouteChildren: LearnCoachRouteChildren = {
  LearnCoachThreadIdRoute: LearnCoachThreadIdRoute,
  LearnCoachIndexRoute: LearnCoachIndexRoute,
}

const LearnCoachRouteWithChildren = LearnCoachRoute._addFileChildren(
  LearnCoachRouteChildren,
)

interface LearnConnectRouteChildren {
  LearnConnectSituationRoute: typeof LearnConnectSituationRoute
  LearnConnectIndexRoute: typeof LearnConnectIndexRoute
}

const LearnConnectRouteChildren: LearnConnectRouteChildren = {
  LearnConnectSituationRoute: LearnConnectSituationRoute,
  LearnConnectIndexRoute: LearnConnectIndexRoute,
}

const LearnConnectRouteWithChildren = LearnConnectRoute._addFileChildren(
  LearnConnectRouteChildren,
)

interface LearnSupportRouteChildren {
  LearnSupportResourceRoute: typeof LearnSupportResourceRoute
  LearnSupportIndexRoute: typeof LearnSupportIndexRoute
}

const LearnSupportRouteChildren: LearnSupportRouteChildren = {
  LearnSupportResourceRoute: LearnSupportResourceRoute,
  LearnSupportIndexRoute: LearnSupportIndexRoute,
}

const LearnSupportRouteWithChildren = LearnSupportRoute._addFileChildren(
  LearnSupportRouteChildren,
)

interface LearnUnderstandRouteChildren {
  LearnUnderstandTopicRoute: typeof LearnUnderstandTopicRoute
  LearnUnderstandIndexRoute: typeof LearnUnderstandIndexRoute
}

const LearnUnderstandRouteChildren: LearnUnderstandRouteChildren = {
  LearnUnderstandTopicRoute: LearnUnderstandTopicRoute,
  LearnUnderstandIndexRoute: LearnUnderstandIndexRoute,
}

const LearnUnderstandRouteWithChildren = LearnUnderstandRoute._addFileChildren(
  LearnUnderstandRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiChatRoute: ApiChatRoute,
  LearnCoachRoute: LearnCoachRouteWithChildren,
  LearnConnectRoute: LearnConnectRouteWithChildren,
  LearnJourneyRoute: LearnJourneyRoute,
  LearnSupportRoute: LearnSupportRouteWithChildren,
  LearnUnderstandRoute: LearnUnderstandRouteWithChildren,
  LearnIndexRoute: LearnIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
