/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnderstandRouteImport } from './routes/understand'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as JourneyRouteImport } from './routes/journey'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as CoachRouteImport } from './routes/coach'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UnderstandIndexRouteImport } from './routes/understand.index'
import { Route as SupportIndexRouteImport } from './routes/support.index'
import { Route as ConnectIndexRouteImport } from './routes/connect.index'
import { Route as CoachIndexRouteImport } from './routes/coach.index'
import { Route as UnderstandTopicRouteImport } from './routes/understand.$topic'
import { Route as SupportResourceRouteImport } from './routes/support.$resource'
import { Route as ConnectSituationRouteImport } from './routes/connect.$situation'
import { Route as CoachThreadIdRouteImport } from './routes/coach.$threadId'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const UnderstandRoute = UnderstandRouteImport.update({
  id: '/understand',
  path: '/understand',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyRoute = JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRoute = CoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UnderstandIndexRoute = UnderstandIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UnderstandRoute,
} as any)
const SupportIndexRoute = SupportIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SupportRoute,
} as any)
const ConnectIndexRoute = ConnectIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConnectRoute,
} as any)
const CoachIndexRoute = CoachIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoachRoute,
} as any)
const UnderstandTopicRoute = UnderstandTopicRouteImport.update({
  id: '/$topic',
  path: '/$topic',
  getParentRoute: () => UnderstandRoute,
} as any)
const SupportResourceRoute = SupportResourceRouteImport.update({
  id: '/$resource',
  path: '/$resource',
  getParentRoute: () => SupportRoute,
} as any)
const ConnectSituationRoute = ConnectSituationRouteImport.update({
  id: '/$situation',
  path: '/$situation',
  getParentRoute: () => ConnectRoute,
} as any)
const CoachThreadIdRoute = CoachThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => CoachRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/coach': typeof CoachRouteWithChildren
  '/connect': typeof ConnectRouteWithChildren
  '/journey': typeof JourneyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRouteWithChildren
  '/understand': typeof UnderstandRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/coach/$threadId': typeof CoachThreadIdRoute
  '/connect/$situation': typeof ConnectSituationRoute
  '/support/$resource': typeof SupportResourceRoute
  '/understand/$topic': typeof UnderstandTopicRoute
  '/coach/': typeof CoachIndexRoute
  '/connect/': typeof ConnectIndexRoute
  '/support/': typeof SupportIndexRoute
  '/understand/': typeof UnderstandIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/journey': typeof JourneyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/chat': typeof ApiChatRoute
  '/coach/$threadId': typeof CoachThreadIdRoute
  '/connect/$situation': typeof ConnectSituationRoute
  '/support/$resource': typeof SupportResourceRoute
  '/understand/$topic': typeof UnderstandTopicRoute
  '/coach': typeof CoachIndexRoute
  '/connect': typeof ConnectIndexRoute
  '/support': typeof SupportIndexRoute
  '/understand': typeof UnderstandIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/coach': typeof CoachRouteWithChildren
  '/connect': typeof ConnectRouteWithChildren
  '/journey': typeof JourneyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRouteWithChildren
  '/understand': typeof UnderstandRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/coach/$threadId': typeof CoachThreadIdRoute
  '/connect/$situation': typeof ConnectSituationRoute
  '/support/$resource': typeof SupportResourceRoute
  '/understand/$topic': typeof UnderstandTopicRoute
  '/coach/': typeof CoachIndexRoute
  '/connect/': typeof ConnectIndexRoute
  '/support/': typeof SupportIndexRoute
  '/understand/': typeof UnderstandIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/coach'
    | '/connect'
    | '/journey'
    | '/sitemap.xml'
    | '/support'
    | '/understand'
    | '/api/chat'
    | '/coach/$threadId'
    | '/connect/$situation'
    | '/support/$resource'
    | '/understand/$topic'
    | '/coach/'
    | '/connect/'
    | '/support/'
    | '/understand/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/journey'
    | '/sitemap.xml'
    | '/api/chat'
    | '/coach/$threadId'
    | '/connect/$situation'
    | '/support/$resource'
    | '/understand/$topic'
    | '/coach'
    | '/connect'
    | '/support'
    | '/understand'
  id:
    | '__root__'
    | '/'
    | '/coach'
    | '/connect'
    | '/journey'
    | '/sitemap.xml'
    | '/support'
    | '/understand'
    | '/api/chat'
    | '/coach/$threadId'
    | '/connect/$situation'
    | '/support/$resource'
    | '/understand/$topic'
    | '/coach/'
    | '/connect/'
    | '/support/'
    | '/understand/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoachRoute: typeof CoachRouteWithChildren
  ConnectRoute: typeof ConnectRouteWithChildren
  JourneyRoute: typeof JourneyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SupportRoute: typeof SupportRouteWithChildren
  UnderstandRoute: typeof UnderstandRouteWithChildren
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/understand': {
      id: '/understand'
      path: '/understand'
      fullPath: '/understand'
      preLoaderRoute: typeof UnderstandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey': {
      id: '/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof JourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/understand/': {
      id: '/understand/'
      path: '/'
      fullPath: '/understand/'
      preLoaderRoute: typeof UnderstandIndexRouteImport
      parentRoute: typeof UnderstandRoute
    }
    '/support/': {
      id: '/support/'
      path: '/'
      fullPath: '/support/'
      preLoaderRoute: typeof SupportIndexRouteImport
      parentRoute: typeof SupportRoute
    }
    '/connect/': {
      id: '/connect/'
      path: '/'
      fullPath: '/connect/'
      preLoaderRoute: typeof ConnectIndexRouteImport
      parentRoute: typeof ConnectRoute
    }
    '/coach/': {
      id: '/coach/'
      path: '/'
      fullPath: '/coach/'
      preLoaderRoute: typeof CoachIndexRouteImport
      parentRoute: typeof CoachRoute
    }
    '/understand/$topic': {
      id: '/understand/$topic'
      path: '/$topic'
      fullPath: '/understand/$topic'
      preLoaderRoute: typeof UnderstandTopicRouteImport
      parentRoute: typeof UnderstandRoute
    }
    '/support/$resource': {
      id: '/support/$resource'
      path: '/$resource'
      fullPath: '/support/$resource'
      preLoaderRoute: typeof SupportResourceRouteImport
      parentRoute: typeof SupportRoute
    }
    '/connect/$situation': {
      id: '/connect/$situation'
      path: '/$situation'
      fullPath: '/connect/$situation'
      preLoaderRoute: typeof ConnectSituationRouteImport
      parentRoute: typeof ConnectRoute
    }
    '/coach/$threadId': {
      id: '/coach/$threadId'
      path: '/$threadId'
      fullPath: '/coach/$threadId'
      preLoaderRoute: typeof CoachThreadIdRouteImport
      parentRoute: typeof CoachRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CoachRouteChildren {
  CoachThreadIdRoute: typeof CoachThreadIdRoute
  CoachIndexRoute: typeof CoachIndexRoute
}

const CoachRouteChildren: CoachRouteChildren = {
  CoachThreadIdRoute: CoachThreadIdRoute,
  CoachIndexRoute: CoachIndexRoute,
}

const CoachRouteWithChildren = CoachRoute._addFileChildren(CoachRouteChildren)

interface ConnectRouteChildren {
  ConnectSituationRoute: typeof ConnectSituationRoute
  ConnectIndexRoute: typeof ConnectIndexRoute
}

const ConnectRouteChildren: ConnectRouteChildren = {
  ConnectSituationRoute: ConnectSituationRoute,
  ConnectIndexRoute: ConnectIndexRoute,
}

const ConnectRouteWithChildren =
  ConnectRoute._addFileChildren(ConnectRouteChildren)

interface SupportRouteChildren {
  SupportResourceRoute: typeof SupportResourceRoute
  SupportIndexRoute: typeof SupportIndexRoute
}

const SupportRouteChildren: SupportRouteChildren = {
  SupportResourceRoute: SupportResourceRoute,
  SupportIndexRoute: SupportIndexRoute,
}

const SupportRouteWithChildren =
  SupportRoute._addFileChildren(SupportRouteChildren)

interface UnderstandRouteChildren {
  UnderstandTopicRoute: typeof UnderstandTopicRoute
  UnderstandIndexRoute: typeof UnderstandIndexRoute
}

const UnderstandRouteChildren: UnderstandRouteChildren = {
  UnderstandTopicRoute: UnderstandTopicRoute,
  UnderstandIndexRoute: UnderstandIndexRoute,
}

const UnderstandRouteWithChildren = UnderstandRoute._addFileChildren(
  UnderstandRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoachRoute: CoachRouteWithChildren,
  ConnectRoute: ConnectRouteWithChildren,
  JourneyRoute: JourneyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SupportRoute: SupportRouteWithChildren,
  UnderstandRoute: UnderstandRouteWithChildren,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
